### ISSUE TITLE
shortcut keys not working

### ISSUE THREAD

**Issue by vigilancetech-com** [kdheepak/taskwarrior-tui#494]
**Describe the bug**

shortcut keys don't work
**To Reproduce**

- [ ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

(no test data needed except for at least one single task in the database)

1. clone the latest taskwarrior and taskwarrior-tui repos
2. build/install both
3. $ task add "my sample task"
4. put 'echo I made it >/tmp/task.txt' in ~/.config/taskwarrior-tui/shortcut-scripts/test.sh
5. chmod +x that file
6. add 'uda.taskwarrior-tui.shortcuts.2=~/.config/taskwarrior-tui/shortcut-scripts/test.sh' to .taskrc
7. start taskwarrior-tui
8. hit the number 2
9. check to see if /tmp/task.txt exists and contains "I made it"

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: latest github releases
- taskwarrior-tui version: 0.23.7

- task version: 2.6.2

**Additional context and information**

taskwarrior-tui fails one test:

```
[kevin@topsail taskwarrior-tui]$ cargo test --bin taskwarrior-tui
   Compiling taskwarrior-tui v0.23.7 (/home/kevin/0work/productivity/taskwarrior-tui)
    Finished test [unoptimized + debuginfo] target(s) in 2.28s
warning: the following packages contain code that will be rejected by a future version of Rust: traitobject v0.1.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running unittests src/main.rs (target/debug/deps/taskwarrior_tui-5a09ad7f64f6cb20)

running 6 tests
test config::tests::test_get_config_last_long_value ... ok
test config::tests::test_colors ... ok
test config::tests::test_get_config_long_value ... ok
test config::tests::test_get_config_long_value_followed_by_default_value ... ok
test app::tests::test_centered_rect ... ok
test app::tests::test_taskwarrior_tui ... FAILED

failures:

---- app::tests::test_taskwarrior_tui stdout ----
thread 'app::tests::test_taskwarrior_tui' panicked at 'Expected task data to be empty but found 1 tasks. Delete contents of "/home/kevin/0work/productivity/taskwarrior-tui/tests/data/.task" and "/home/kevin/0work/productivity/taskwarrior-tui/tests/data/.config" and run the tests again.', src/app.rs:3901:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: taskwarrior_tui::app::tests::_test_taskwarrior_tui::{{closure}}
             at ./src/app.rs:3901:9
   3: taskwarrior_tui::app::tests::test_taskwarrior_tui::{{closure}}
             at ./src/app.rs:3895:54
   4: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/park/thread.rs:263:54
   5: tokio::coop::with_budget::{{closure}}
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
   6: std::thread::local::LocalKey<T>::try_with
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/thread/local.rs:446:16
   7: std::thread::local::LocalKey<T>::with
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/thread/local.rs:422:9
   8: tokio::coop::with_budget
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:95:5
   9: tokio::coop::budget
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
  10: tokio::park::thread::CachedParkThread::block_on
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/park/thread.rs:263:31
  11: tokio::runtime::enter::Enter::block_on
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/enter.rs:152:13
  12: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/mod.rs:90:9
  13: tokio::runtime::Runtime::block_on
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/mod.rs:484:43
  14: taskwarrior_tui::app::tests::test_taskwarrior_tui
             at ./src/app.rs:3891:17
  15: taskwarrior_tui::app::tests::test_taskwarrior_tui::{{closure}}
             at ./src/app.rs:3890:31
  16: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    app::tests::test_taskwarrior_tui

test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s

error: test failed, to rerun pass `--bin taskwarrior-tui`
[kevin@topsail taskwarrior-tui]$ 
```

**Comment by kdheepak** [comment]
Thanks for reporting! That’s odd. Maybe my version of task is old? I’ll try upgrading and look into this.
