### ISSUE TITLE
Unable to run ./taskwarrior-tui

### ISSUE THREAD

**Issue by c02y** [kdheepak/taskwarrior-tui#7]
Following the steps in README:
```
Manual

    1. Download the tar.gz file for your OS from the latest release.
    2. Unzip the tar.gz file
    3. Run with ./taskwarrior-tui.
```
Output:
```
thread 'main' panicked at 'Unable to run `task show`: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/color.rs:118:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
⏎
```

Running with `RUST_BACKTRACE=1` : 
```
thread 'main' panicked at 'Unable to run `task show`: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/color.rs:118:22
stack backtrace:
fish: “env RUST_BACKTRACE=1 ./taskwarr…” terminated by signal SIGSEGV (Address boundary error)
⏎ 
```

**Comment by kdheepak** [comment]
You have `taskwarrior` installed? Can you run `task show` from your command line? What is the output of `task show?

**Comment by c02y** [comment]
You didn't mention `taskwarrior-tui` depends on `taskwarrior`, I thought you rewrite the whole `taskwarrior` with extra tui feature using rustlang.

Now, I get, I should install `taskwarrior` first.

**Comment by kdheepak** [comment]
Thanks, I'll update the README to reflect this!
